import { z } from "zod";

export const PROMOTION_STATUS_ENUM = ["active", "inactive", "expired"] as const;

// Schema for creating a promotion
// Based on ReqPromotionDTO, promotionId is usually generated by BE
// Status might be determined by BE based on dates, or can be explicitly set.
export const CreatePromotionBody = z.object({
  promotionCode: z.string().min(1, "Promotion code is required"),
  promotionDescription: z.string().optional(),
  promotionName: z.string().min(1, "Promotion name is required"),
  discount: z.number().min(0, "Discount must be non-negative"),
  startDate: z
    .string()
    .refine((val) => !isNaN(Date.parse(val)), {
      // Assuming ISO string from date picker
      message: "Invalid start date",
    })
    .optional(), // BE defaults to Instant.now() if null
  validity: z.string().refine((val) => !isNaN(Date.parse(val)), {
    // Assuming ISO string
    message: "Invalid validity date",
  }),
  status: z.enum(PROMOTION_STATUS_ENUM).optional(), // Status can be auto-calculated or set
});

export type CreatePromotionBodyType = z.TypeOf<typeof CreatePromotionBody>;

// Schema for a single promotion (aligns with ReqPromotionDTO from BE)
export const PromotionSchema = z.object({
  promotionId: z.number(),
  promotionCode: z.string(),
  promotionDescription: z.string().nullable().optional(),
  promotionName: z.string(),
  discount: z.number(),
  startDate: z.string(), // Instant from BE, usually represented as ISO string
  validity: z.string(), // Instant from BE
  status: z.enum(PROMOTION_STATUS_ENUM),
});

export type PromotionSchemaType = z.TypeOf<typeof PromotionSchema>;

export const PromotionRes = z.object({
  data: PromotionSchema, // For single promotion
  message: z.string().optional(), // Optional message
});
export type PromotionResType = z.TypeOf<typeof PromotionRes>; // More accurately ReqPromotionDTO

// Schema for promotion list response (matches ResultPaginationDTO from BE)
export const PromotionListRes = z.object({
  statusCode: z.number(), // These were in PermissionListRes, adapt if your BE sends them
  error: z.string().nullable(),
  message: z.string(),
  meta: z.object({
    page: z.number(),
    pageSize: z.number(),
    pages: z.number(),
    total: z.number(),
  }),
  result: z.array(PromotionSchema), // In BE, this is 'result' field holding List<ReqPromotionDTO>
});

export type PromotionListResType = z.TypeOf<typeof PromotionListRes>;

// Schema for updating a promotion
// It's similar to CreatePromotionBody but promotionId is handled in the URL/mutation params.
export const UpdatePromotionBody = CreatePromotionBody.extend({
  // No need to redefine fields if they are the same.
  // `status` can be part of the general update.
});
export type UpdatePromotionBodyType = z.TypeOf<typeof UpdatePromotionBody>;

// Schema for updating promotion status specifically
export const UpdatePromotionStatusBody = z.object({
  status: z.enum(PROMOTION_STATUS_ENUM),
});
export type UpdatePromotionStatusBodyType = z.TypeOf<
  typeof UpdatePromotionStatusBody
>;

// Schema for promotion parameters (e.g., ID in URL)
export const PromotionParams = z.object({
  id: z.coerce.number(),
});
export type PromotionParamsType = z.TypeOf<typeof PromotionParams>;
